### ISSUE TITLE
make easily guide for install your cms on free IaaS service providers simple like openshift rhc

### ISSUE THREAD

**Issue by syntox** [jarves/jarves#3]
hi Marc 
At the first time , special thanks to develop this amazing but i'm want to deploy it on free services
& I,m littlebit request for example install it for me on my openshift consule :)
if you agree my request , pv to me to send you login detail
sorry for my bad english
thanks for taking your time m8
goodbye

**Comment by marcj** [comment]
I don't think there is a web based installer anytime soon that works on system you don't have console access. Although there is an old version https://github.com/jarves/jarves/blob/master/Resources/meta/installation-wizard.php.dist I don't think it's still working as its very outdated, especially since you still need to `composer install` all the things.

**Comment by syntox** [comment]
thanks so much dude , so intresting to become new webased easy setup release
